deepgram/deepgram-js-sdk

- src/transcription/liveTranscription.ts
Normal closure is 1000 rather than 0 (https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent)
> Fix ws close code

- README.md
Currently, the README explains using the constructor as:
```js
const deepgram = new Deepgram({
apiKey: DEEPGRAM_API_KEY,
apiUrl: CUSTOM_API_URL, // Optionally used for on-premises customers
});
```
Two things of note:
1. The constructor doesn't accept an object. It accepts two strings: `apiKey` & `apiUrl`.
2. Because the SDK only targets the beta Deepgram API, the `apiUrl` parameter is irrelevant at the moment.
Because of the above, I modified the code to read:
```js
const deepgram = new Deepgram(DEEPGRAM_API_KEY);
```
> Correcting constructor documentation in README. Closes #4

- CHANGELOG.md
- src/keys.ts
- src/types/createKeyOptions.ts
- src/types/index.ts
- tests/keys.test.ts
Updated the `keys.create` function to allow new `expirationDate` or `timeToLive` values. These are optional and one at most can be provided. Providing both will throw an error.
> Added the ability to create temporary keys

- CHANGELOG.md
- package-lock.json
- package.json
- src/transcription/liveTranscription.ts
Our `finish` function was not sending a final message that would tell Deepgram to finalize the stream. This would result in users not getting the final transcript.
Closes #23
> Fixing real-time socket close bug

- CHANGELOG.md
- src/types/utterance.ts
- src/types/wordBase.ts
- Updated the `wordBase` type to include an optional `speaker` property.
- Updated the documentation for the speaker property of the `utterance` type.
> Updating wordBase object to add speaker

- src/keys.ts
- src/types/key.ts
- src/types/keyResponse.ts
- src/types/member.ts
updated the API key type to match the current API response
fixes #25
> fix: fix types to match current api response

- CHANGELOG.md
- src/types/liveTranscriptionOptions.ts
- src/types/prerecordedTranscriptionOptions.ts
The `version` parameter was typed as required for both pre-recorded and live transcription. Changed this to be optional.
> Fixing version parameter of transcription options

- CHANGELOG.md
- src/types/liveTranscriptionOptions.ts
- src/types/prerecordedTranscriptionOptions.ts
Added tier to the type definitions of accepted options for live and prerecorded transcriptions
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201885737791795/1202569827943128) by [Unito](https://www.unito.io)
> Added tier to the type definitions of accepted options for live and prerecorded transcriptions

- src/httpRequest.ts
- src/transcription/preRecordedTranscription.ts
- src/types/transcriptionSource.ts
- tests/transcription/preRecordedTranscription.test.ts
So I know when I opened the original issue I requested that ReadStream be added as a TranscriptionSource, but on usage, I realize that it's useful to use the stream.Readable for more flexibility.
Since the code doesn't actually rely on added methods, and Readable being a superclass should mean any type checks continue to work, this can be implemented as a non-breaking change.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201885737791795/1202445230557606) by [Unito](https://www.unito.io)
> Change ReadStreamSource to accept stream.Readable instead of only fs.ReadStream.

- CHANGELOG.md
- package-lock.json
- package.json
- sample/index.js
- webpack.config.js
The bundling of type definitions was preventing the types from exporting the Deepgram class by default like the SDK does. Rolled back bundling of the type definitions. The package now publishing the Node SDK, browser SDK, and non-bundled type definitions.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Fixing issue with type files not exporting Deepgram class

- src/types/liveTranscriptionOptions.ts
- src/types/prerecordedTranscriptionOptions.ts
Here's the public API docs for our Redaction feature:
`pci`: Redacts sensitive credit card information, including credit card number, expiration date, and CVV
`numbers (or true)`: Aggressively redacts strings of numerals
`ssn`: Redacts social security numbers
It doesn't accept an array of parameters so I defined it as string or boolean to support `true`.
We could also do `redact?: 'pci' | 'numbers' | 'ssn' | true;` but that may be more of a breaking change.
> Fix redaction types

- package.json
The built bundle of this package is missing the `dist/browser/transcription` folder, which means that `dist/browser/index.d.ts` cannot get the right typing information for `Deepgram.transcription` so that gets typed as `any`. This can be seen by going to https://unpkg.com/browse/@deepgram/sdk@1.17.0/dist/browser/ and noticing the missing folder.
The root cause as far as I can tell seems to be how `copyfiles` handles glob expansion where if an argument is unquoted, then it allows the calling shell to handle it which can have unexpected results, especially when going through npm. The general suggestion I've seen previously has been to always quote arguments that have globs for these sorts of tools as they usually then fallback to something like …
> Fix built bundle not including nested browser types

- src/types/liveTranscriptionOptions.ts
Endpointing now accepts either a boolean or a number representing the amount of time to wait before sending back a message with speech_final.
> update endpointing types to match new API

- src/transcription/liveTranscription.ts
- src/types/liveTranscriptionOptions.ts
- src/types/prerecordedTranscriptionOptions.ts
- tests/transcription/preRecorded.test.ts
CFE identified a need to allow certain (will remain nameless) properties to be passed through to the API while avoiding baking in those properties to our type definitions.
> Support arbitrary properties in request

- src/index.ts
Updates to the Deepgram constructor to use `??` instead of `||`.  This change makes the SDK compatible with onprem for streaming (batch needs additional updates).  The `apiUrl` could probably be left as `||`, but `requireSSL` needs to be the "nullish coalescing" operator `??` as otherwise if set to "False" for the onprem case the `||` operator will still default to the default option.
> Use nullish coalescing

- src/projects.ts
- tests/projects.test.ts
- tests/scopes.test.ts
- tests/usage.test.ts
All but one method for projects accepts the project_id, but the project.update method accepts the whole project object, plus another object with changes.
In the API, we only send over the changes object with the project_id.
I am modifying this method to accept project_id, uniformly with our other project methods, but retaining the backwards compatibility in the developer surface.
> fix: uniform method format, backwards compatible

- src/types/liveTranscriptionOptions.ts
- src/types/prerecordedTranscriptionOptions.ts
The SDK currently accepts a string, but this should allow multiple strings. `querystring.stringify` handles the rest, which is possibly why this has only come up as someone has tried to do it in TypeScript and find it doesn't like it.
fixes #145
> fix: find-and-replace can accept multiple strings

- src/types/metadata.ts
- src/types/prerecordedTranscriptionResponse.ts
- src/types/warning.ts
Add typing for new response format supporting summarisation results and warning metadata.
e.g. output
```json
{
"metadata": {
...
"warnings": [
{
"parameter": "summarize",
"type": "unsupported_language",
"message": "Summarization isn’t supported for <detected language>."
}
]
},
"results": {
...
"summary": {
"result": "failure",
"short": "The summarization feature is currently only available in English. Please check out our API documentation for more details."
}
}
}
```
and 
```json
{
"metadata": {
...
"warnings": [
{
"parameter": "filler_words",
"type": "unsupported_model",
"message": "Filler Words is not available for the specified model. For supported models, see our docs: <link>"
},
{
"parameter": "numerals",
"type": "deprecated",
"message": "The numerals parameter is deprecated. …
```
> feat: add warning metadata and summarisation result to response type

- .github/workflows/CD.yml
This, SHOULD, prevent the CD workflow from running for pre-releases of the SDK. This is so we can manually release them, and not accidentally update @latest with a prelease.
> chore: don't run workflow for pre-releases [skip ci]

- .github/workflows/CI.yml
- src/index.ts
This PR adds types and enums to the exports of the main module. This allows a user to require types and enums along with the main `createClient` factory, to use them in client applications.
before:
```
const { createClient } = require("@deepgram/sdk");
const { LiveTranscriptionEvents } = require("@deepgram/sdk/dist/main/lib/enums");
// or
import { createClient } from "@deepgram/sdk";
import { LiveTranscriptionEvents } from "@deepgram/sdk/dist/main/lib/enums";
```
after:
```
const { createClient, LiveTranscriptionEvents } = require("@deepgram/sdk");
// or
import { createClient, LiveTranscriptionEvents } from "@deepgram/sdk";
```
> feat: export types and enums from main module

- src/lib/types/LiveTranscriptionEvent.ts
The `LiveTranscriptionEvent` type specifies that the `alternatives` and `words` nested fields are tuples of length 1, when they should be variable length arrays.
> fix(types): nested arrays in LiveTranscriptionEvent

- package-lock.json
- package.json
- src/packages/LiveClient.ts
Such is the unique way that Node and JS differ on their WebSocket interfaces, this will attempt one and fall-back to the other if a syntax error is caught. Not great, but it works. I consider this a temporary solution to finding a library that handles WebSockets correctly in an isomorphic library.
> fix: allow the client to work in either websocket environment

- README.md
- src/packages/AbstractClient.ts
- feat: tightly couple the api key to the proxy logic, so an api can't mistakenly be made public.
- chore: update proxy details in the readme file
> feat: tightly couple the api key to the proxy logic

- src/packages/LiveClient.ts
Removing unnecessary complexity from the WebSocket close event. We've yet to encounter a need for this logic, while it is also not compatible with edge functions. Removing it fixes edge functions close events. 
Fixes #210
> fix: remove unnecessary complexity from close event

- src/lib/types/SyncPrerecordedResponse.ts
This was missing from the channel definition.
PSA: It's possible this also affects other SDKs
fixes #212
> fix: add missing type to channel interface

- src/lib/types/LiveTranscriptionEvent.ts
Incorrectly typed confidence on live event alternative definition.
Fixes 213
> fix: mistyped definition for alternative confidence on live event

- src/DeepgramClient.ts
- src/index.ts
- src/lib/errors.ts
- test/legacy.test.ts
> feat: throw errors when using v2 callstack on the v3 SDK

- examples/node-live/index.js
fixes #223 
Catch Errors and log them
> chore: update live example to include error event

- src/lib/helpers.ts
- src/lib/types/AnalyzeSchema.ts
- src/lib/types/AsyncAnalyzeResponse.ts
- src/lib/types/DeepgramSource.ts
- src/lib/types/SyncAnalyzeResponse.ts
- src/lib/types/SyncPrerecordedResponse.ts
- src/lib/types/TranscriptionSchema.ts
- src/lib/types/index.ts
- src/packages/PrerecordedClient.ts
- src/packages/ReadClient.ts
fixes #190
fixes #191
fixes #192
fixes #193
fixes #194
fixes #195
fixes #196
> feat: sits for JS sdk

- src/lib/enums/LiveTranscriptionEvents.ts
- src/lib/types/TranscriptionSchema.ts
- src/lib/types/UtteranceEndEvent.ts
- src/lib/types/index.ts
- src/packages/LiveClient.ts
> feat: add UtteranceEnd event to sdk

- src/lib/types/TranscriptionSchema.ts
> fix: allows endpointing to be disabled with a value of false

- examples/node-live/index.js
- src/DeepgramClient.ts
- src/index.ts
- src/lib/enums/LiveTranscriptionEvents.ts
- src/lib/errors.ts
- src/lib/helpers.ts
- src/lib/types/AnalyzeSchema.ts
- src/lib/types/AsyncAnalyzeResponse.ts
- src/lib/types/DeepgramSource.ts
- src/lib/types/SpeechStartedEvent.ts
- src/lib/types/SyncAnalyzeResponse.ts
- src/lib/types/SyncPrerecordedResponse.ts
- src/lib/types/TranscriptionSchema.ts
- src/lib/types/UtteranceEndEvent.ts
- src/lib/types/index.ts
- src/packages/AbstractClient.ts
- src/packages/AbstractRestfulClient.ts
- src/packages/LiveClient.ts
- src/packages/ReadClient.ts
- test/legacy.test.ts
- feat: add missing feature toggles from q1 feature audit (#237)
- feat: add speechstarted event to sdk (#235)
- fix: allows endpointing to be disabled with a value of false (#236)
- feat: add UtteranceEnd event to sdk (#234)
- feat: sits for JS sdk (#233)
- chore: update live example to include error event (#231)
- feat: improve experience around usage of custom API endpoints (#230)
- feat: throw errors when using v2 callstack on the v3 SDK (#226)
> January minor release

- src/lib/constants.ts
Small fix to the permanent warning when someone has not provided a custom URL (make the default URL not trigger the warning by adding a protocol).
> fix: default URL should have protocol included

- examples/node-speak/index.js
- src/DeepgramClient.ts
- src/lib/types/SpeakSchema.ts
- src/lib/types/index.ts
- src/packages/AbstractRestfulClient.ts
- src/packages/SpeakClient.ts
This PR adds functionality for the speak endpoint, including:
- `getStream()` method to get just the TTS audio stream
- `getHeaders()` method to get just the TTS response headers
- example code that demonstrates how to get the response, get the stream, and get the headers. It also shows how to take the stream, convert it to a buffer and then write it to an audio file
> feat: speak endpoint added

- src/lib/constants.ts
- src/lib/fetch.ts
- src/lib/types/DeepgramClientOptions.ts
- src/packages/AbstractRestfulClient.ts
- test/client.test.ts
This PR renames `fetch` to `fetchOptions` and adds an additional option to provide own fetch method. 
fixes #243
> feat: add fetch override

- examples/node-live/index.js
This is an improved version to make it easier to understand the docs [here](https://developers.deepgram.com/docs/understand-endpointing-interim-results)
Users tend to not understand how to handle these things and our samples do not include how it works
What types of changes does your code introduce to the community Python SDK?
_Put an `x` in the boxes that apply_
> Handle is_final and endpointing together with utterance end

- src/lib/types/CreateProjectKeyResponse.ts
When creating ephemeral keys with a ttl, the API returns a response to `v1/projects/:projectId/keys` with an `expiration_date` param. This adds that response to the type.
> Add missing expiration_date to CreateProjectKeyResponse type

- examples/node-live/index.js
- package-lock.json
- src/lib/constants.ts
- src/lib/fetch.ts
- src/lib/types/CreateProjectKeyResponse.ts
- src/lib/types/DeepgramClientOptions.ts
- src/lib/types/GetTokenDetailsResponse.ts
- src/lib/types/index.ts
- src/packages/AbstractRestfulClient.ts
- src/packages/ManageClient.ts
- test/client.test.ts
- feat: add _experimentalCustomFetch config to override fetch (#245)
- chore: Bump es5-ext from 0.10.62 to 0.10.64  (#250)
- feat: add get auth token details method to manage client (#262)
- chore: edit example for is_final and endpointing together with utterance end (#264)
- fix: update user agent to include JS or node (#269)
> feat: Release/3.x.x 20240427

- examples/browser-prerecorded/index.html
- webpack.config.js
fixes #274 
writing the node version at build to the browser scope, as we don't report on it anyway. nice quick fix.
> fix: process is undefined error in browsers

- src/lib/constants.ts
The `process` global does not exist in the browser and therefore throws an error if one tries to create a client in the browser.
Fix it in a way that's compatible with any (future) engine that doesn't have a process global.
closes #290
> fix: unconditional process reference

- src/lib/constants.ts
Follow up to close #297 
- check if `process` is defined, else fall back to `Unknown`
- prevent the unlikely case of `process.versions` being defined without a `node` key, fall back to `Unknown`
> fix: Resolve missing process variable in browser environment

- src/lib/types/SyncPrerecordedResponse.ts
will fixes this issue https://github.com/deepgram/deepgram-js-sdk/issues/260
> fix: missing `speaker` type in SyncPrerecordedResponse 

- src/packages/LiveClient.ts
- We already do toLowerCase(), so don't need `i` flag.
- We're not using the http bit, so no need to capture it.
- If there's an s, append it, if not don't. This is the same as just replacing http with ws:
- [http]:// -> [ws]://
- [http]s:// -> [ws]s://
- [http]x:// -> [ws]x:// -> error. Is ok.
- [http]sx:// -> [ws]sx:// -> error in both. Is ok.
- We don't want to replace protocols that do not start with http, such as git+https, so we can anchor at string start and leave out the `g` flag.
Much simpler -:)
> chore: simplify regex

- src/lib/types/TranscriptionSchema.ts
fixes #295 
adds missing type definition for restricting language detection to an array of language codes
> fix: missing type for detect_language which supports multiple strings OR a single bool

- src/packages/AbstractLiveClient.ts
Mismatch client protocol when using Bun native Websockets. If bun env is detected we replace native websocket with "ws"
> Update AbstractLiveClient.ts to close #317

- src/lib/constants.ts
- src/lib/helpers.ts
- src/packages/AbstractLiveClient.ts
When testing the streaming example we found that the BUN changes had introduced a regression for the browser code.
*screams in isomorphic*
> fix: process is not defined in browser demos right now

- src/DeepgramClient.ts
- src/lib/types/GetModelsResponse.ts
- src/lib/types/GetModelsSchema.ts
- src/lib/types/index.ts
- src/packages/ManageRestClient.ts
- src/packages/ModelsRestClient.ts
- src/packages/index.ts
- test/manage_rest.test.ts
- test/models_rest.test.ts
adds new metadata get model endpoints to the JS SDK
> feat: new metadata models endpoints

- src/packages/AgentLiveClient.ts
Noticed `updatePrompt` was still using `instructions`. The [the v1 spec](https://github.com/deepgram/VA-API-Spec-v1) expects `prompt`. This updates it to align with the spec.
Ties up the earlier rename from `updateInstructions` → `updatePrompt`.
> fix: instructions -> prompt in updatePrompt to align with v1 spec
