CHANGELOG.md
package-lock.json
package.json
src/helpers/index.ts
src/helpers/secondsToTimestamp.ts
src/transcription/preRecordedTranscription.ts
src/types/prerecordedTranscriptionResponse.ts

Added two helper methods to prerecorded transcription objects. Transcribing with the `utterances` feature is required to use these.
Example usage:
```js
const { Deepgram } = require('@deepgram/sdk');
const deepgram = new Deepgram(DG_API_KEY);
const transcription = await deepgram.transcription.preRecorded({
url: 'https://static.deepgram.com/examples/Bueller-Life-moves-pretty-fast.wav'
}, {
punctuate: true,
utterances: true
});
console.log(transcription.toWebVTT());
console.log(transcription.toSRT());
```
Those consoles will return:
```
WEBVTT
NOTE
Transcription provided by Deepgram
Request Id: 23c1f8de-640e-41bc-b324-7f94d3b2efbf
Created: 2021-10-31T02:14:20.392Z
Duration: 17.56631
Channels: 1
1
00:00:05.700 --> 00:00:05.859
- Yep.
2
00:00:07.274 --> 00:00:09.250
- I said it before, and …
```

Adding WebVTT & SRT helper functions

---

README.md

Updates the README.md code sample for streaming to have the correct variable name.

README.md code fix (transcription -> received)

---

CHANGELOG.md
package-lock.json
package.json
src/types/liveTranscriptionOptions.ts
src/types/prerecordedTranscriptionOptions.ts

Added replace param to options

Replace param

---

package-lock.json
package.json

Modified package.json script to deploy all type definitions, not just those in the root of the build output.

Adding missing types

---

CODE_OF_CONDUCT.md

Update to latest version of COC

---

tests/keys.test.ts

Hello, I've chosen to bypass creating an issue for this because I believe it is a pretty trivial test change.
I noticed in `CONTRIBUTING.md` that one of the requirements for contributions to be accepted is that they follow existing styling conventions in the code base. While working through a separate ticket I noticed there was some inconsistency in the styling of callbacks for `describe`, `it`, etc functions. Most test files used arrow functions but some tests in the `keys.test.ts` file used function declarations (some functions in the same file even used arrow functions as well). 
I know this is kind of a nitpick, so feel free to push back if you don't believe this is necessary. but I thought changing everything to be consistent across all test files may help future contributors ensure …

updates `keys.test.ts` to make code style consistent across all test files

---

package-lock.json
src/httpRequest.ts

Fixing bug in httprequest

---

README.md

I found a minor issue on the README file. I copied and pasted the code snippet for live transcription on my project, but it didn't work. I believe it requires a few adjustments, which I propose in this pull request.

Fixed code snippet for live transcription found in the README file. 

---

src/types/liveTranscriptionOptions.ts
src/types/prerecordedTranscriptionOptions.ts
src/types/usageOptions.ts
src/types/usageRequestDetail.ts

@briancbarrow I'm not sure if this also needs to be added to `usageRequest.ts` and `usageRequestDetail.ts`—let me know.

add smart formatting

---

src/types/alternatives.ts
src/types/channel.ts

moving detected_language to correct type

---

package-lock.json
package.json
src/helpers/secondsToTimestamp.ts
src/types/prerecordedTranscriptionResponse.ts

- doesn't include diarize
- doesn't do paragraphs
- requires utterances

feat: Better VTT and SRT

---

README.md

adds discord badge

---

src/packages/LiveClient.ts

fix: closing the socket too early

---

src/lib/helpers.ts
src/packages/LiveClient.ts

- fix: closing the socket too early (#201)
- fix: a wild fix for this has appeared (#200)

fix: fixes issues 197 and 198

---

README.md
package-lock.json
package.json
src/index.ts
src/packages/LiveClient.ts

- feat: update websocket to use w3cwebsocket client
- chore: update readme to link to migration guide
- chore: update readme to include async callback examples

feat: update websocket to use w3cwebsocket client

---

src/lib/types/LiveTranscriptionEvent.ts
src/lib/types/SyncPrerecordedResponse.ts
src/packages/LiveClient.ts

Multiple post-release bug fixes

---

src/packages/AbstractClient.ts
src/packages/AbstractRestfulClient.ts

feat: improve experience around usage of custom API endpoints

---

src/lib/enums/LiveTranscriptionEvents.ts
src/lib/types/SpeechStartedEvent.ts
src/lib/types/index.ts
src/packages/LiveClient.ts

feat: add SpeechStarted event to sdk

---

src/lib/types/SyncAnalyzeResponse.ts
src/lib/types/SyncPrerecordedResponse.ts

fix: metadata response missing from analyze response

---

src/lib/constants.ts

fix: update user agent to include JS or node

---

src/packages/ListenLiveClient.ts

fix: correct spelling of LiveClient

---

src/packages/AbstractClient.ts

Amends 501d6d08028c9fb805707516c0d168de8ae91acc.
Fixes #309.

fix: use correct import of EventEmitter

---

package-lock.json
package.json
src/lib/types/TranscriptionSchema.ts

Pretty straight-forward... just adding `no_delay` to streaming options.

feat: implement `no_delay`

---

src/lib/types/LiveTranscriptionEvent.ts
src/lib/types/SyncPrerecordedResponse.ts

This is also pretty straight-forward. This implements the multi-lingual response for Live and PreRecorded Transcription.

feat: implement multi-lingual

---

README.md

BREAKING CHANGE: the interfaces for the voice agent have changed.

feat: release voice agent v1
